# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177D66bEZZ0xqxJw2xQnnx9ueZaawW5zy
"""

!wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update -q
!apt-get install -y google-chrome-stable
!apt-get install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

# Install chromedriver that matches Chrome 146
!pip install webdriver-manager

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

def create_driver():
    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")

    # This automatically downloads the correct chromedriver for your Chrome version
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    return driver

# Quick test
driver = create_driver()
driver.get("https://www.google.com")
print("✅ Chrome is working! Title:", driver.title)
driver.quit()

!pip install selenium webdriver-manager

import time, csv, re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager

OUTPUT_FILE = "results.csv"
CSV_HEADERS = ["Job_Title","Company_Title","Company_Slogan","Job_Type","Location",
               "Work_Location","Industry","Employes_Count","Posted_Ago","Job_Link"]
BASE_URL = "https://www.welcometothejungle.com/en/jobs?refinementList%5Boffices.country_code%5D%5B%5D=US&query=Business"

def create_driver():
    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36")
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    return driver

def clean_posted_ago(v):
    return "1 days ago" if v and v.strip().lower() == "yesterday" else v

def clean_employees(v):
    if v:
        return re.sub(r'\s+', ' ', re.sub(r'\bemployees?\b', '', v, flags=re.IGNORECASE)).strip()
    return v

def safe_get(driver, xpath, default=""):
    try:
        return driver.find_element(By.XPATH, xpath).text.strip()
    except:
        return default

def close_popup(driver):
    try:
        btn = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH,
            "//button[contains(translate(.,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'close') or "
            "contains(translate(.,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'accept')]"
        )))
        btn.click()
        time.sleep(1)
    except:
        pass

# ── STEP 1: Collect all job links from listing pages ──
def collect_all_links(driver):
    links = set()
    driver.get(BASE_URL)
    time.sleep(4)
    close_popup(driver)

    page = 1
    while True:
        print(f"  Collecting links from page {page}...")
        # Scroll to load all cards
        for _ in range(4):
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(1.5)

        # Get all job links on current page
        anchors = driver.find_elements(By.XPATH, "//a[contains(@href,'/en/companies/') and contains(@href,'/jobs/')]")
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/jobs/" in href:
                links.add(href.split("?")[0])  # remove query params

        print(f"    Total links so far: {len(links)}")

        # Next page
        try:
            next_btn = driver.find_element(By.XPATH,
                "//a[@rel='next'] | //button[@aria-label='Next page'] | //a[contains(@aria-label,'Next')]")
            if next_btn.is_enabled() and next_btn.is_displayed():
                driver.execute_script("arguments[0].click();", next_btn)
                time.sleep(3)
                page += 1
            else:
                break
        except:
            print("  ✅ No more pages.")
            break

    return list(links)

# ── STEP 2: Visit each job page and scrape details ──
def scrape_job_page(driver, url):
    try:
        driver.get(url)
        time.sleep(2.5)
        page_text = driver.find_element(By.TAG_NAME, "body").text

        # Job Title
        job_title = ""
        for xp in ["//h1", "//h2[1]"]:
            try:
                job_title = driver.find_element(By.XPATH, xp).text.strip()
                if job_title: break
            except: continue

        # Company Title
        company_title = ""
        for xp in [
            "//a[contains(@href,'/en/companies/')]//span",
            "//a[contains(@href,'/en/companies/')]",
            "//span[@data-testid='company-name']"
        ]:
            try:
                company_title = driver.find_element(By.XPATH, xp).text.strip()
                if company_title: break
            except: continue

        # Company Slogan
        company_slogan = ""
        try:
            paras = driver.find_elements(By.XPATH, "//p | //h3 | //h4")
            for p in paras:
                t = p.text.strip()
                if t and t != job_title and t != company_title and 15 < len(t) < 200:
                    company_slogan = t
                    break
        except: pass

        # Job Type
        job_type = ""
        for kw in ["Permanent Contract","Internship","Freelance","Temporary","Apprenticeship","VIE","Full-Time","Part-Time"]:
            if kw.lower() in page_text.lower():
                job_type = kw
                break

        # Location
        location = ""
        loc_match = re.search(r'([A-Z][a-zA-Z\s]+,\s*[A-Z]{2,})', page_text)
        if loc_match:
            location = loc_match.group(1).strip()

        # Work Location
        work_location = ""
        for kw in ["Full remote","Partial remote","Remote","Hybrid","On-site"]:
            if kw.lower() in page_text.lower():
                work_location = kw
                break

        # Industry
        industry = ""
        try:
            ind = driver.find_element(By.XPATH,
                "//*[contains(@class,'industry') or contains(@class,'sector') or contains(@data-testid,'industry')]")
            industry = ind.text.strip()
        except: pass

        # Employee Count
        emp_raw = ""
        emp_match = re.search(r'(\d[\d,]*\s*[-–]?\s*\d*[\d,]*\+?\s*employees?)', page_text, re.IGNORECASE)
        if emp_match:
            emp_raw = emp_match.group(1)
        else:
            rng = re.search(r'(\d+\s*[-–]\s*\d+)\s*(?:people|employees|members)?', page_text, re.IGNORECASE)
            if rng: emp_raw = rng.group(1)

        # Posted Ago
        posted = ""
        p_match = re.search(r'(\d+\s+(?:days?|hours?|weeks?|months?)\s+ago|yesterday|today|just now)', page_text, re.IGNORECASE)
        if p_match: posted = p_match.group(1)

        # Clean (Step 6)
        posted = clean_posted_ago(posted)
        emp_cleaned = clean_employees(emp_raw)

        return {
            "Job_Title": job_title,
            "Company_Title": company_title,
            "Company_Slogan": company_slogan,
            "Job_Type": job_type,
            "Location": location,
            "Work_Location": work_location,
            "Industry": industry,
            "Employes_Count": emp_cleaned,
            "Posted_Ago": posted,
            "Job_Link": url,
        }
    except Exception as e:
        print(f"  ⚠️ Error on {url}: {e}")
        return {h: "" for h in CSV_HEADERS} | {"Job_Link": url}

# ── MAIN ──
print("🚀 Starting scraper...")
driver = create_driver()

try:
    print("\n📋 Phase 1: Collecting all job links...")
    all_links = collect_all_links(driver)
    print(f"✅ Found {len(all_links)} job links\n")

    print("📋 Phase 2: Scraping each job page...")
    all_jobs = []
    for i, link in enumerate(all_links, 1):
        print(f"  [{i}/{len(all_links)}] {link[-60:]}")
        job = scrape_job_page(driver, link)
        all_jobs.append(job)
        time.sleep(1)  # be polite to the server

    # Save CSV
    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_HEADERS)
        writer.writeheader()
        writer.writerows(all_jobs)
    print(f"\n✅ Saved {len(all_jobs)} records to {OUTPUT_FILE}")

    # ── ANSWERS ──
    import pandas as pd
    df = pd.read_csv(OUTPUT_FILE, dtype=str).fillna('')
    print("\n" + "="*55)
    print("📊 ANSWERS FOR SUBMISSION FORM")
    print("="*55)
    print(f"(a) Total jobs: {len(df)}")
    print(f"(b) Jobs in New York: {len(df[df['Location'].str.contains('new york', case=False)])}")
    more200 = less200 = 0
    for v in df['Employes_Count']:
        nums = [int(n) for n in re.findall(r'\d+', v.replace(',',''))]
        if nums:
            if max(nums) > 200: more200 += 1
            if min(nums) < 200: less200 += 1
    print(f"(c) Companies > 200 employees: {more200}")
    print(f"(d) Companies < 200 employees: {less200}")
    print(f"(e) Permanent Contract: {len(df[df['Job_Type'].str.contains('permanent', case=False)])}")
    print(f"(f) Internship: {len(df[df['Job_Type'].str.contains('internship', case=False)])}")
    print("="*55)

finally:
    driver.quit()
    print("\n🏁 Done!")

from google.colab import files
files.download("results.csv")

